config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :pages, param: :slug do
    resources :versions
  end

  resources :search, only: [:index, :q]
  post '/pages/:page_slug/versions/new' => 'versions#create'
  patch '/pages/:page_slug/' => 'pages#update'

  get '/search' => 'search#index'

  get '/tags' => 'tags#index'
  get '/tags/:tag' => 'tags#show'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post 'markdown_renderer/transform', controller: :markdown_renderer
    end
  end

end

app/views/pages/_form.html.slim
= form_for @page do |f|
  - unless @err.nil?
    #error_explanation.alert.alert-danger role="alert"
      p = "#{@err.message}"


  .field.form-group
    = f.label :page_slug, "Page slug (friendly URL)"
    .input-group
      .input-group-addon = "/pages/"
      = f.text_field :page_slug, class: "form-control", value: @page[:page_slug] || SecureRandom.uuid
  .field.form-group
    = f.label :title
    = f.text_field :title, class: "form-control input-lg"
  .field.form-group
    = f.label :tags
    = f.text_field :tags, class: "form-control", value: @page.tags.try(:join, ", "), placeholder: "tags, in, comma, separated"
  = render partial: "pages/form_body", locals: { initial_value: (@page.body || @page.versions.first.try(:body) || @initial_body), form: f }
  .actions = f.submit class: "btn btn-primary", id: "form-pages-new-submit"

== javascript_include_tag 'pages/new'

app/views/pages/_form_body.html.slim
.field.form-group
  = form.label :body
  .row
    .col-sm-6
      = form.text_area :body, class: "form-control markdown-input", id: "form-pages-new-body", value: initial_value, rows: 20
    .col-sm-6
      .panel.panel-default.page-view
        .panel-heading
          | Preview
          .pull-right
            label.checkbox-inline
              input#form-pages-new-autoupdate type="checkbox" checked="checked" Auto Update
            #form-pages-new-manualupdate.btn.btn-info.btn-xs Update
        #form-pages-new-body-preview.panel-body.markdown-body
          h3 Preview will appear here

app/views/pages/_panel_list_view.html.slim
.panel.panel-default.page-view
  .panel-heading
    .pull-right
      p #{pluralize page.versions.count, "version"}, #{full_time_ago page.updated_at}
    .text-left
      h4 = link_to page.title, show_page_path(page)
    .tags
      - page.tag_list.each do |tag|
        span.label.label-default
          = link_to tag, show_tag_path(tag)
  .panel-body.markdown-body
    - if snip
      == PagesController.rendor_mkd body.split(/\r?\n/)[0,5].join("\n")
      small
        mark
          = link_to "(#{body.split(/\r?\n/).size} lines in total)", show_page_path(page)
    - else
      == PagesController.rendor_mkd body

app/views/pages/edit.html.slim
- provide :title, "Editing #{@page.title}"

ol.breadcrumb
  li = link_to "Home", root_path
  li = link_to @page.title, @page
  li.active Edit

= form_for @page, url: page_update_path(@page) do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title, class: "form-control"
  .field
    = f.label :tag_list
    = f.text_field :tag_list, class: "form-control", value: @page.tags.join(", ")
  .actions = f.submit class: "btn btn-primary"
hr
- if @page.deleted_at.nil?
  = link_to "Archive Page", @page, method: :delete, class: "btn btn-danger"
- else
  = link_to "This page has been archived", @page, method: :delete, class: "btn btn-danger disabled"

app/views/pages/index.html.slim
- provide :title, "All pages"

ol.breadcrumb
  li = link_to "Home", root_path
  li.active All pages (#{page_entries_info @pages})

= paginate @pages, theme: 'twitter-bootstrap-3'

- @pages.each do |page|
  = render partial: "panel_list_view", locals: { page: page, body: page.versions.first.body, snip: true }

= paginate @pages, theme: 'twitter-bootstrap-3'

app/views/pages/new.html.slim
- provide :title, "Create new page"

- breadcrumb :new_page

== render 'form'

app/views/pages/show.html.slim
- provide :title, @page.title

ol.breadcrumb
  li = link_to "Home", root_path
  li.active #{@page.title} (latest @ #{full_time_ago @page.versions.first.created_at})

- if params[:notice]
  #notice.alert.alert-info = params[:notice]

- unless @page.deleted_at.nil?
  .alert.alert-warning
    | This page was archived at #{full_time_ago @page.deleted_at}

.panel.panel-default.page-view
  .panel-heading
    .pull-right
      .btn-group.no-print
        = link_to edit_page_path(@page), class: "btn btn-primary", "role" => "button" do
          span.glyphicon.glyphicon-pencil
          | Update
        = link_to edit_page_meta_path(@page), class: "btn btn-default", "role" => "button" do
          span.glyphicon.glyphicon-cog
          | Edit
        = link_to fork_page_path(@page), class: "btn btn-info", "role" => "button" do
          span.glyphicon.glyphicon-duplicate
          | Fork
        = link_to page_versions_path(@page), class: "btn btn-default" do
          span.glyphicon.glyphicon-th-list
          | History
          .badge = @page.versions.size
    h2 = @page.title
    .tags
      - @page.tag_list.each do |tag|
        span.label.label-default
          = link_to tag, show_tag_path(tag)
  .panel-body.markdown-body == PagesController.rendor_mkd @page.versions.first[:body]