config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :pages, param: :slug do
    resources :versions
  end

  resources :search, only: [:index, :q]
  post '/pages/:page_slug/versions/new' => 'versions#create'
  patch '/pages/:page_slug/' => 'pages#update'

  get '/search' => 'search#index'

  get '/tags' => 'tags#index'
  get '/tags/:tag' => 'tags#show'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      post 'markdown_renderer/transform', controller: :markdown_renderer
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = ActsAsTaggableOn::Tag.where('taggings_count > ?', 0)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @pages = @pages_with_tag.page params[:page]
  end

  def tag_cloud
    @tags = Page.tag_counts_on(:tags)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = params[:tag]
    @pages_with_tag = Page.tagged_with(@tag).order('pages.updated_at DESC')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params[:tag]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.slim
- provide :title, "All tags"

ol.breadcrumb
  li = link_to "Home", root_path
  li.active All tags

.tags-list
  - tag_cloud(@tags, %w{label-info label-success label-warning label-danger}) do |tag, css_class|
    span class="tag label label-tag #{css_class}" = link_to show_tag_path(tag.name) do
      = tag.name
      span.badge.tags_count = tag.taggings_count

app/views/tags/show.html.slim
- provide :title, "Tag: #{@tag}"

ol.breadcrumb
  li = link_to "Home", root_path
  li = link_to "All tags", tags_path
  li.active #{@tag} (#{page_entries_info @pages})

= paginate @pages, theme: 'twitter-bootstrap-3'

- @pages.each do |page|
  = render partial: "pages/panel_list_view", locals: { page: page, body: page.versions.first.body, snip: true }

= paginate @pages, theme: 'twitter-bootstrap-3'